 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.zensar.student.exception;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.context.request.WebRequest;
import org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler;

public class CustomerGlobalException extends ResponseEntityExceptionHandler {
   @ExceptionHandler({InvalidCustomerOrderIdException.class, InvalidFoodItemIdException.class, InvalidMenuIdException.class})
   public ResponseEntity<Object> handleException(RuntimeException ex, WebRequest request) {
      return this.handleExceptionInternal(ex, "{\"error\": \"" + ex.toString() + "\"}", new HttpHeaders(), HttpStatus.BAD_REQUEST, request);
   }
}
