 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.zensar.student.exception;

public class InvalidFoodItemIdException extends RuntimeException {
   private String message;

   public InvalidFoodItemIdException() {
      this.message = "";
   }

   public InvalidFoodItemIdException(String message) {
      this.message = message;
   }

   public String toString() {
      return "Food item id is not found " + this.message;
   }
}
