 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.zensar.student.exception;

public class InvalidCustomerOrderIdException extends RuntimeException {
   private String message;

   public InvalidCustomerOrderIdException() {
      this.message = "";
   }

   public InvalidCustomerOrderIdException(String message) {
      this.message = message;
   }

   public String toString() {
      return "Customer order id is not found " + this.message;
   }
}
