 // Source code is unavailable, and was generated by the Fernflower decompiler.
package com.zensar.student.service;

import com.zensar.student.dto.CustomerOrder;
import com.zensar.student.entity.CustomerOrderEntity;

 public interface CustomerOrderService {
   CustomerOrder createCustomerOrder(CustomerOrder customerOrder);

   CustomerOrder getCustomerOrderById(int orderId);
}
